config/routes.rb
Binda::Engine.routes.draw do

  # ROOT
  # ----
  # https://github.com/plataformatec/devise/wiki/How-To:-Require-authentication-for-all-components
  # https://stackoverflow.com/a/24135199/1498118
  authenticated :user do
    root to: "boards#dashboard"
  end
  unauthenticated :user do
    devise_scope :user do
      get "/", to: "users/sessions#new"
    end
  end

  # DEVISE
  # ------
  # https://github.com/plataformatec/devise/blob/88724e10adaf9ffd1d8dbfbaadda2b9d40de756a/lib/devise/rails/routes.rb#L143
  devise_for :users, class_name: "Binda::User", module: 'binda/users',
  path_names: { 
    sign_in: 'login', 
    sign_out: 'logout', 
    password: 'secret', 
    confirmation: 'verification', 
    unlock: 'unblock', 
    registration: 'register',
    sign_up: 'signup'
  }

  namespace :manage do
    resources :users
  end

  # ADMINISTRATION PANEL
  # --------------------
  get  'dashboard', to: 'boards#dashboard', as: :dashboard

  post 'structures/sort'
  get 'structures/sort_index'
  resources :structures do
    post 'field_groups/sort'
    post 'field_groups/add_child'
    post 'sort_field_groups'
    post 'add_field_group'
    resources :field_groups do
      post 'field_settings/add_child'
      post 'field_settings/sort'
      post 'sort_field_settings'
      post 'add_field_setting'
      resources :field_settings
    end
    resources :boards do
      post 'sort_repeaters'
      post 'new_repeater'
      member do
        patch 'upload'
      end
    end
    post 'components/sort'
    get 'components/sort_index'
    resources :components do
      post 'sort_repeaters'
      post 'new_repeater'
      member do
        patch 'upload'
      end
    end
    resources :categories
  end

  resources :choices, only: [:destroy]

  resources :audios do
    member do
      delete 'remove_audio'
    end
  end
  resources :videos do
    member do
      delete 'remove_video'
    end
  end
  resources :images do
    member do
      delete 'remove_image'
    end
  end
  resources :svgs do
    member do
     delete 'remove_svg'  
    end
  end
  resources :repeaters

end

app/models/binda/application_record.rb
# require deprecations list which can be found in app/models/concerns/binda/deprecations.rb
require 'binda/deprecations'

module Binda
  class ApplicationRecord < ActiveRecord::Base
    self.abstract_class = true
  end
end

app/models/binda/asset.rb
module Binda
	# Assets is a parent class which isn't directly used but can be referenced to gather 
	# all the classes that deal with files.
  class Asset < ApplicationRecord

  	include Fields
    include FieldReadonly
  end
end

app/models/binda/association_field.rb
module Binda
  class AssociationField < ApplicationRecord

    belongs_to :associable, polymorphic: true

    # children_fieldable_relates "names" the Association join table for accessing through the children_fieldable association
    has_many :active_relationships, class_name: "Relationship", dependent: :destroy, as: :children_fieldable
    # parent_fieldable_relates "names" the Association join table for accessing through the parent_fieldable association
    has_many :passive_relationships, class_name: "Relationship", dependent: :destroy, as: :parent_fieldable

=begin
    # source: :children_fieldable matches with the belong_to :children_fieldable identification in the Association model
    has_many :children_fieldables, class_name: "Component", through: :passive_relationships, source: :children_fieldable, source_type: "Binda::Component"
    # source: :parent_fieldable matches with the belong_to :children_fieldable identification in the Association model
    has_many :parent_fieldables, class_name: "Component", through: :active_relationships, source: :parent_fieldable, source_type: "Binda::Component"
=end

    # source: :children_fieldable matches with the belong_to :children_fieldable identification in the Association model
    has_many :children_fieldables_component, through: :passive_relationships, source: :children_fieldable, source_type: "Binda::Component"
    # source: :parent_fieldable matches with the belong_to :children_fieldable identification in the Association model
    has_many :parent_fieldables_component, through: :active_relationships, source: :parent_fieldable, source_type: "Binda::Component"


    # source: :children_fieldable matches with the belong_to :children_fieldable identification in the Association model
    has_many :children_fieldables_board, through: :passive_relationships, source: :children_fieldable, source_type: "Binda::Structure"
    # source: :parent_fieldable matches with the belong_to :children_fieldable identification in the Association model
    has_many :parent_fieldables_board, through: :active_relationships, source: :parent_fieldable, source_type: "Binda::Structure"
=begin
    # source: :children_fieldable matches with the belong_to :children_fieldable identification in the Association model
    has_many :children_fieldables, class_name: "Board", through: :passive_relationships, source: :children_fieldable, source_type: "Binda::Board"
    # source: :parent_fieldable matches with the belong_to :children_fieldable identification in the Association model
    has_many :parent_fieldables, class_name: "Board", through: :active_relationships, source: :parent_fieldable, source_type: "Binda::Board"
=end


=begin
    validates :parent_fieldable_id, presence: true
    validates :children_fieldable_id, presence: true
=end

    validates :name, presence: true
    validates :slug, presence: true

  end
end

app/models/binda/audio.rb
module Binda
	# This class provides support for uploading videos.
	class Audio < Asset

    mount_uploader :audio, AudioUploader
  end
end

app/models/binda/b.rb
module Binda
	# This provides a convenient way to access Binda [default helpers](http://www.rubydoc.info/gems/binda/Binda/DefaultHelpers).
	class B < ApplicationRecord
		include DefaultHelpers
	end
end

app/models/binda/binda.rb
module Binda
  module Binda
    def self.table_name_prefix
      'binda_binda_'
    end
  end
end

app/models/binda/board.rb
module Binda
  class Board < ApplicationRecord

  	include FieldableAssociations

		belongs_to :structure, required: true

		validates :name, presence: true
		validates :slug, uniqueness: true

		# Slug
		extend FriendlyId
		friendly_id :name, use: [:slugged, :finders]

		# Friendly id preference on slug generation
		#
		# Method inherited from friendly id 
		# @see https://github.com/norman/friendly_id/issues/436
		def should_generate_new_friendly_id?
			slug.blank?
		end

		def self.remove_orphans
			Board
				.includes(:structure)
				.where(binda_structures: {id: nil})
				.each do |b|
				b.destroy!
				puts "Binda::Board with id ##{b.id} successfully destroyed"
			end
    end

    # Create field instances for the current component
    def create_field_instances
      CreateFieldInstancesJob.perform_later self
    end

  end
end

app/models/binda/category.rb
module Binda
  class Category < ApplicationRecord

  	# Associations
  	belongs_to :structure
  	has_and_belongs_to_many :components

		# Validations
		validates :name, presence: true
		validates :structure_id, presence: true

  	# Slug
		extend FriendlyId
		friendly_id :default_slug, use: [:slugged, :finders]


		# Friendly id preference on slug generation
		#
		# Method inherited from friendly id 
		# @see https://github.com/norman/friendly_id/issues/436
	  def should_generate_new_friendly_id?
	    slug.blank? || name_changed?
	  end

		# Set slug name
		#
		# It generates 4 possible slugs before falling back to FriendlyId default behaviour
	  def default_slug
	  	[ "#{ self.structure.name }-#{ self.name }",
	  		"#{ self.structure.name }-#{ self.name }-1",
	  		"#{ self.structure.name }-#{ self.name }-2",
	  		"#{ self.structure.name }-#{ self.name }-3" ]
	  end

  end
end

app/models/binda/checkbox.rb
module Binda
	# This class provides support for checkboxes and depends on `Binda::Selection`.
	# You can find more info at the _selection_ [documentation](http://www.rubydoc.info/gems/binda/Binda/Selection)
	class Checkbox < Selection

	end
end

app/models/binda/choice.rb
module Binda
	# Choices are used in **select**, **radio** and **checkboxes** and defined by a **field setting**. 
	#
	# The architecture of this class is a bit complex and deserves some attention:
	#   Here the rules that defines the class behaviour:
	# 
	# 1. **Choices** must be associated to a **field setting**
	# 2. Every **choice** can be associated to several **select/radio/checkbox**
	# 3. (This is tricky) Assuming you are going to delete a choice and 1) **field setting** requires at least one choice
	#   2) some **select/checkbox/radio** are associated just to that **choice**. To be able to do it you must first replace 
	#   that **choice** on those **select/checkbox/radio**. Only then you can delete that **choice**.
	#   
	# The **default choice** is applied only to field that requires at least a **choice**.
  class Choice < ApplicationRecord

  	belongs_to :field_setting
  	has_and_belongs_to_many :selections

		validates :label, presence: {
			message: I18n.t('binda.choice.label_validation_message')
		}
		validates :value, presence: {
			message: I18n.t('binda.choice.value_validation_message')
		}
		validates :field_setting_id, presence: {
			message: I18n.t('binda.choice.field_setting_id_validation_message')
		}

		before_destroy :check_last_choice
		after_create :set_default_choice
		after_destroy :reset_default_choice

		# Some field setting requires at least one choice. To avoid leaving this kind of field setting without
		#   any choice, a validation checks that there is at least an alternative choice that will become the default one.
		# This validation is skipped when deleting the field setting from which the choice depends because choice are 
		#   deleted directly from database (see `dependent: :delete_all`).
		def check_last_choice
			if !self.field_setting.allow_null? && Choice.where(field_setting_id: self.field_setting.id).length == 1
				errors.add(:base, I18n.t('binda.choice.validation_message.destroy'))
				throw(:abort)
			end
		end

		# In order to make sure that a default choice is set, this method is executed after
		#   the first choice is associated to the field setting. What does it do? 
		#   If there isn't a default it sets the current choice as the default one.
		#   The method is executed as well if new choices are added.
		def set_default_choice
			# Make sure you are referring to the updated ActiveRecord object where the choice has already been deleted
			#	Infact: self.field_setting != FieldSetting.find( self.field_setting.id )
			field_setting = FieldSetting.find(self.field_setting.id)
			if field_setting.default_choice_id.nil? && !field_setting.allow_null?
				# if field_setting.field_type = 'radio' 
				field_setting.default_choice_id = self.id
				unless field_setting.save
					raise "It hasn't been possible to set the default choice for the current setting (#{field_setting.slug})."
				end
				assign_choice_to_selections(field_setting, self)
			end
		end

		# Assign a choice to `Binda::Selection` items belonging to a specific field setting.
		# 
		# TODO it shouldn't be possible to add another choice to a radio button. 
		#   The only reasonable way is to change has_many association in a has_one
		# 
		# @param field_setting [Binda::FieldSetting]
		# @param new_default_choice [Binda::Choice]
		def assign_choice_to_selections(field_setting, new_default_choice)
			Selection.where(field_setting_id: field_setting.id).each do |selection|
				selection.choices << new_default_choice
				unless selection.save
					raise "It hasn't been possible to set the default choice for #{selection.class.name} with id=#{selection.id}."
				end
			end
		end

		# In order to make sure a default choice is set, this method is executed after the 
		#   default choice is removed. What does it do? If the removed choice is the default one it sets
		#   another defautl picking the first of the choices associated by id. 
		#   Once done, update all associated records that now don't have the any associated choice.
		#   
		# This method doesn't run when a field setting is destroyed as the association is
		#   `Binda::FieldSetting has_many :choices, dependent: :delete_all` not `dependent: :destory`. 
		#   That means the `after_destroy` callback for Binda::Choice (and this method as well) won't run.
		def reset_default_choice
			# Make sure you are referring to the updated ActiveRecord object where the choice has already been deleted
			#	Infact: self.field_setting != FieldSetting.find(self.field_setting.id)
			field_setting = FieldSetting.find(self.field_setting.id)

			# Don't do anything if the default choice isn't the one we just destroyed
			return if field_setting.choice_ids.include?(field_setting.default_choice_id)
			
			# Make sure the default choice is needed
			return if field_setting.allow_null? && field_setting.field_type != 'radio'

			if field_setting.choices.any?
				# Mark as default choice the first choice available
				update_default_choice(field_setting, field_setting.choices.first.id)
			else
				warn("WARNING: Binda::FieldSetting \"#{field_setting.slug}\" doesn't have any default choice! Please set a new default choice and then run the following command from Rails Console to update all related Binda::Selection records: \nrails binda:add_default_choice_to_all_selections_with_no_choices")
				# Remove default choice setting (which at this point is the current choice (self))
				update_default_choice(field_setting, nil)
			end

			# Update all selection records which depend on the deleted choice
			Selection.check_all_selections_depending_on(field_setting)
		end

		private 

			# Update field setting with a default choice
			# 
			# This is private method for reset_default_choice method.
			# 
			# @param field_setting [ActiveRecord Object]
			def update_default_choice(field_setting, id)
				# Update and check if it's alright
				unless field_setting.update(default_choice_id: id) 
					raise "It hasn't been possible to set the default choice for the current setting (#{field_setting.slug})." 
				end
			end

  end
end

app/models/binda/component.rb
module Binda
	class Component < ApplicationRecord

		include FieldableAssociations

		# Associations

		belongs_to :structure, required: true
		has_and_belongs_to_many :categories

		# Validations
		validates :name, presence: true
		validates :slug, uniqueness: true
		validates :publish_state, presence: true, inclusion: { in: %w( draft published )}

		accepts_nested_attributes_for :categories, allow_destroy: true

		after_create :set_default_position
		after_create :create_field_instances

		# Slug
		extend FriendlyId
		friendly_id :name, use: [:slugged, :finders]

		# Publish state behaviour
		include AASM

			aasm :column => 'publish_state' do
					state :draft, initial: true
					state :published

				event :publish do
					transitions from: :draft, to: :published
				end

				event :unpublish do
					transitions from: :published, to: :draft
				end

			end

		# Friendly id preference on slug generation
		#
		# Method inherited from friendly id
		# @see https://github.com/norman/friendly_id/issues/436
		def should_generate_new_friendly_id?
			slug.blank?
		end

		# The limit above which componets cannot be sorted anymore
		def self.sort_limit
			1000
		end

    # Create field instances for the current component
    def create_field_instances
      CreateFieldInstancesJob.perform_later self
		end

		def self.remove_orphans
			Component
				.includes(:structure)
				.where(binda_structures: {id: nil})
				.each do |c|
					c.destroy!
					puts "Binda::Component with id ##{c.id} successfully destroyed"
				end
		end

		private

			def set_default_position
				Component
					.where(structure_id: self.structure_id)
					.update_all('position = position + 1')
			end

	end
end

app/models/binda/date.rb
module Binda
	# This class provides support for dates.
  class Date < ApplicationRecord

    include Fields
    include FieldUniqueness
		
  end
end

app/models/binda/deprecation.rb
module Binda
	class Deprecation < ActiveSupport::Deprecation
		def initialize(deprecation_horizon = 'next major release', gem_name = 'Binda')
			super
		end
	end
end

app/models/binda/gallery.rb
module Binda
  class Gallery < ApplicationRecord

    include Fields
    include FieldUniqueness

  end
end

app/models/binda/image.rb
module Binda
	# This class provides support for uploading images.
  class Image < Asset

    mount_uploader :image, ImageUploader

    # Register image details
    # 
    # Do not delete. This method is used by a rake task
    def register_details
      if !self.image.present?
        warn "Ops, there is no image for Binda::Image id=#{self.id}"
      elsif CarrierWave::Uploader::Base.storage == CarrierWave::Storage::File
        file = MiniMagick::Image.open(::Rails.root.join(self.image.path))
        register_details_of(file)
      else
        file = MiniMagick::Image.open(self.image.url)
        register_details_of(file)
      end
    end
    
    # Register image details
    # 
    # This method is used by register_details in a rake task
    def register_details_of(file)
      self.file_width = file.width
      self.file_height = file.height
      self.content_type = file.mime_type if file.mime_type
      self.file_size = file.size
      self.save!
      puts "Updated image details for Binda::Image id=#{self.id}"
    end

  end
end

app/models/binda/radio.rb
module Binda
	# This class provides support for radio buttons and depends on `Binda::Selection`.
	# You can find more info at the _selection_ [documentation](http://www.rubydoc.info/gems/binda/Binda/Selection)
	class Radio < Selection

	end
end

app/views/binda/pages/_asset_field.html.erb
<% current_asset = page.assets.where( field_setting_id: field_setting.id ).first %>
<% unless current_asset.present? %>
	<% current_asset = page.assets.create( field_setting_id: field_setting.id )%>
<% end %>

<%= f.simple_fields_for "assets_attributes[]", current_asset do |ff|%>
	<div class="asset-form">

		<h5><%= field_setting.name.capitalize %></h5>

		<% if current_asset.image.present? && current_asset.image.thumb.file.exists? %>
      <%= image_tag current_asset.image.thumb.url %>
		<% end %>

		<% unless field_setting.description.blank? %>
			<small class="text-muted"><%= field_setting.description %></small>
		<% end %>

		<%= ff.input :image, input_html: { class: 'asset-form--uploader'} %>

    <%= ff.input :image_cache, as: :hidden %>
		<%= ff.input :field_setting_id, as: :hidden, input_html: { value: field_setting.id } %>
		<%= ff.input :id, as: :hidden, input_html: { value: current_asset.id } %>

	</div>
<% end %>

app/views/binda/pages/_date_field.html.erb
<% current_date = page.dates.where( field_setting_id: field_setting.id ).first %>
<% unless current_date.present? %>
	<% current_date = page.dates.create( field_setting_id: field_setting.id )%>
<% end %>

<%= f.simple_fields_for "dates_attributes[]", current_date do |ff|%>

	<%= ff.input :field_setting_id, as: :hidden, input_html: { value: field_setting.id } %>
	<%= ff.input :id, as: :hidden, input_html: { value: current_date.id } %>

	<h5><%= field_setting.name.capitalize %></h5>

	<% unless field_setting.description.blank? %>
		<small class="text-muted"><%= field_setting.description %></small>
	<% end %>

	<%= ff.input :date, start_year: Date.today.year - 200, end_year: Date.today.year + 200 %>

<% end %>

app/views/binda/pages/_form.html.erb
  <div class="row">
    <div class="form-inputs col-sm-12">
      
      <%= simple_form_for page, url: get_form_page_url, defaults: { label: false }, html: { class: 'parent-group-form' } do |f| %>
        <%= f.error_notification %>
        
        <div class="row">
          <div class="col-sm-8">

            <div class="form-inputs--row form-inputs--wide row">
              <div class="col-sm-12">

                <h4><%= "#{ t :details }".capitalize %></h4>

                <h5><%= "#{ t :title }".capitalize %></h5>
                <%= f.input :name %>
                
                <% if page.slug.nil? %>
                  <%= f.input :slug, as: :hidden %>
                <% else %>
                  <h5><%= "#{ t :slug }".capitalize %></h5>
                  <%= f.input :slug, disabled: true, hint: "#{ t :slug_disable_hint }" %>
                <% end %>

                <%= f.input :structure_id, as: :hidden, input_html: { value: @structure.id } %>
                
              </div>
            </div>
            
            <%= render "parent_group", parent_group: @structure, f: f, page: page %>

          </div>
          <div class="col-sm-4">

            <div class="form-inputs--row form-inputs--narrow row">
              <div class="col-sm-12">
                <h4><%= "#{ t :setting }".pluralize.capitalize %></h4>

                <% if @structure.categories.any? %>

                  <h5><%= t(:category).capitalize %></h5>
                  <%= f.association :categories, as: :radio_buttons, collection: @structure.categories ,checked: page.category_ids, include_blank: false %>

                <% end %>

                <% if page.slug.nil? %>
                  <h5>
                    <%= t( :hint_create_parent_before_child, arg1: "#{ t :category }", arg2: "#{ t :page }" ).capitalize %>  
                  </h5>
                <% else %>
                  <a class="main-header--link btn btn-default" href="<%= new_structure_category_path %>">
                    <%= "#{ t :new }".capitalize %> <%= t :category %>  
                  </a>
                <% end %>

                <hr>

                <h5><%= t(:publish_settings).capitalize %></h5>
                <%= f.input :publish_state, as: :radio_buttons, collection: [ 'draft', 'published' ], checked: f.object.publish_state %>

                <hr>

                <%= f.button :submit, 'Save changes', class: 'btn btn-primary' %>
              </div>
            </div>
            
          </div>
        </div>
      
      <% end %>

    </div>
  </div>

app/views/binda/pages/_gallery_field.html.erb
<% # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # %>
<% # # # # # # # # # # # # # TUTTO DA FARE # # # # # # # # # # # # # # # %>
<% # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # %>

<% current_gallery = page.galleries.where( field_setting_id: field_setting.id ).first %>
<% unless current_gallery.present? %>
	<% current_gallery = page.galleries.create( field_setting_id: field_setting.id )%>
<% end %>


<%= f.simple_fields_for "assets_attributes[]", current_gallery do |ff|%>
  <div class="parent-group-form--child">

		<%= ff.input :field_setting_id, as: :hidden, input_html: { value: field_setting.id } %>
		<%= ff.input :id, as: :hidden, input_html: { value: current_gallery.id } %>

		<h5><%= field_setting.name.capitalize %></h5>

		<% unless field_setting.description.blank? %>
			<small class="text-muted"><%= field_setting.description %></small>
		<% end %>

		<%= ff.input :position %>
    <%= ff.input :image_cache %>

  </div>
<% end %>









<% # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # %>
<% if false %>


<%= f.simple_fields_for 'new_galleries[]', page.galleries.build() do |ff| %>
  <div id="new-child-1" class="parent-group-form--child parent-group-form--new-child">

		<%= ff.input :field_setting_id, as: :hidden, input_html: { value: field_setting.id } %>
		<%= ff.input :id, as: :hidden, input_html: { value: current_gallery.id } %>

		<h5><%= field_setting.name.capitalize %></h5>

		<% unless field_setting.description.blank? %>
			<small class="text-muted"><%= field_setting.description %></small>
		<% end %>

		<%= ff.input :image %>

  </div>
<% end %>

<% if page.slug.nil? %>
  <h5>
    <%= t( :hint_create_parent_before_child, arg1: "#{ t :page }", arg2: "#{ t :gallery }" ).capitalize %>  
  </h5>
<% else %>
  <a class="parent-group-form--add-child main-header--link btn btn-default" href="<%= new_structure_page_path( page_id: page.slug ) %>" data-new-child-id="new-child-1">
    <%= "#{ t :new }".capitalize %> <%= t :gallery %>  
  </a>
<% end %>



<% end %>
<% # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # %>

app/views/binda/pages/_parent_group.html.erb
<% parent_group.field_groups.order( :position ).each_with_index do |field_group, index| %>
<div class="form-inputs--row form-inputs--wide row">
  <div class="col-sm-12">

    <h4><%= field_group.name.capitalize %></h4>

    <% if page.new_record? %>

      <h5><%= t( :hint_create_parent_before_child, arg1: "#{ t :page }", arg2: "#{ t :detail }" ).capitalize %></h5>
    
    <% else %>

      <% field_group.field_settings.order( :position ).each do |field_setting| %>

        <% if field_setting.field_type == 'text' || field_setting.field_type == 'string' %>
          <%= render 'text_field', f: f, page: page, field_setting: field_setting %>
        <% end %>
        <% if field_setting.field_type == 'date' %>
          <%# render 'date_field', f: f, page: page, field_setting: field_setting %>
        <% end %>
        <% if field_setting.field_type == 'repeater' %>
          <%# render 'repeater_field', f: f, page: page, field_setting: field_setting %>
        <% end %>
        <% if field_setting.field_type == 'asset' %>
          <%# render 'asset_field', f: f, page: page, field_setting: field_setting %>
        <% end %>

      <% end %>
    
    <% end %>
      
  </div>
</div>
<% end %>

app/views/binda/pages/_text_field.html.erb
<% current_text = page.texts.where( field_setting_id: field_setting.id ).first %>
<% unless current_text.present? %>
	<% current_text = page.texts.create( field_setting_id: field_setting.id )%>
<% end %>

<%= f.simple_fields_for "texts_attributes[]", current_text do |ff|%>

	<%= ff.input :field_setting_id, as: :hidden, input_html: { value: field_setting.id } %>
	<%= ff.input :id, as: :hidden, input_html: { value: current_text.id } %>

	<h5><%= field_setting.name.capitalize %></h5>

	<% unless field_setting.description.blank? %>
		<small class="text-muted"><%= field_setting.description %></small>
	<% end %>

	<% if page.has_text( field_setting.slug ) %>
		<% if field_setting.field_type == 'text' %>
			<%= ff.input :content, input_html: { value: page.get_text( field_setting.slug ), class: 'tinymce' }, as: :text %>
		<% else %>
			<%= ff.input :content, input_html: { value: page.get_text( field_setting.slug ) }, as: :string %>
		<% end %>
	<% else %>
		<% if field_setting.field_type == 'text' %>
			<%= ff.input :content, input_html: { class: 'tinymce' }, as: :text %>
		<% else %>
			<%= ff.input :content, as: :string %>
		<% end %>
	<% end %>

<% end %>